apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-prod
  name: web-svc
  namespace: prod
spec:
  ports:
  - name: jenkins-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-prod
  type: LoadBalancer
status:
  loadBalancer: {}
