apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  selector:
    matchLabels:
      app: app-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
  type: LoadBalancer
